### ISSUE TITLE
use local eslint if available

### ISSUE THREAD

**Issue by hugomrdias** [TheSavior/ESLint-Formatter#1]
this would be very useful relying on the system global module may be the best option

**Comment by TheSavior** [comment]
What do you get when running `which eslint` from your command line?

**Comment by TheSavior** [comment]
Closed due to inactivity. Feel free to provide more information if this is still a problem.

**Comment by insin** [comment]
The use case for this is not requiring ESLint to be installed globally, and even if it is installed globally, using a locally-available version first if present. This allows you to have different projects managing their own version of ESLint rather than being tied to the same global version.

This is how SublimeLinter does it, for reference: https://github.com/SublimeLinter/SublimeLinter3/blob/7bca95fb79edd038acfa17982495745245af4d7f/lint/node_linter.py#L104

**Comment by TheSavior** [comment]
That looks great. I'd happily accept a pull request adding this. That should also enable it to work with locally installed eslint plugins. I've been using the project specific plugin settings to set the path to my node_modules version.

**Comment by xwartz** [comment]
This pull fix it.

https://github.com/TheSavior/ESLint-Formatter/pull/13

**Comment by platinumazure** [comment]
@TheSavior Looks like the pull request didn't close this issue.

**Comment by TheSavior** [comment]
Should be fixed in 2.1.0 per https://github.com/TheSavior/ESLint-Formatter/pull/13
