### ISSUE TITLE
--fix doesn't work well

### ISSUE THREAD

**Issue by beast** [TheSavior/ESLint-Formatter#2]
I have verified the lint debug view that my node path and eslint path is correct. I also verified manually running the eslint works. My question is that upon fixing the file, it simply push my indent for the tab size i set in eslint config but it did not delete the bad spaces. What is your experience so far, I know I should probably go ahead ask eslint team but was wondering if this is the expected behavior...

**Comment by TheSavior** [comment]
Do you get the same result when you run fix from the eslint CLI directly? If so, it is definitely something that the ESLint team should be made aware of. Otherwise, it is likely a problem with this plugin.

I'm still personally using the JSCS-Formatter but will be moving more to ESLint over the next few months as they merge. http://eslint.org/blog/2016/04/welcoming-jscs-to-eslint

**Comment by beast** [comment]
Sorry, this is a bit late but yeah it's the same result. I'll give it a try after they finally merge. Thanks!
